  services:
    sparkmaster:
      image: bitnami/spark:latest
      container_name: sparkmaster
      command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
      ports:
        - "8060:8080"  # Spark Master UI
        - "7067:7077"  # Spark Master Cluster Port
        - "4060:4040"  # Spark Job UI
      volumes:
        - ./spark_data:/opt/bitnami/spark/work
        - ./spark_events:/opt/bitnami/spark/spark-events  
      environment:
        - SPARK_HISTORY_OPTS="-Dspark.eventLog.enabled=true -Dspark.eventLog.dir=/opt/bitnami/spark/spark-events"
      networks:
        - spark-network

    sparkworker1:
      image: bitnami/spark:latest
      container_name: sparkworker1
      command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
      depends_on:
        - sparkmaster
      mem_limit: 4G  # Adjust based on host (e.g., 8g if host has 16GB+)
      mem_reservation: 2G  # Minimum memory reservation
      cpus: "2"  # Limit to host capacity (e.g., 2 CPUs)
      ports:
        - "8061:8081"  # Spark Worker UI
      volumes:
        - ./spark_data:/opt/bitnami/spark/work
        - ./spark_events:/opt/bitnami/spark/spark-events  # Share event logs
      environment:
        - SPARK_WORKER_CORES=2
        - SPARK_WORKER_MEMORY=4G
        - SPARK_MASTER=spark://sparkmaster:7077
        - SPARK_HISTORY_OPTS="-Dspark.eventLog.enabled=true -Dspark.eventLog.dir=/opt/bitnami/spark/spark-events 
      networks:
        - spark-network
    sparkworker2:
      image: bitnami/spark:latest
      container_name: sparkworker2
      command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
      depends_on:
        - sparkmaster
      mem_limit: 4G  # Adjust based on host (e.g., 8g if host has 16GB+)
      mem_reservation: 2G  # Minimum memory reservation
      cpus: "2"  # Limit to host capacity (e.g., 2 CPUs)
      ports:
        - "8062:8082"  # Spark Worker UI
      volumes:
        - ./spark_data:/opt/bitnami/spark/work
        - ./spark_events:/opt/bitnami/spark/spark-events  # Share event logs
      environment:
        - SPARK_WORKER_CORES=2
        - SPARK_WORKER_MEMORY=4G
        - SPARK_MASTER=spark://sparkmaster:7077
        - SPARK_HISTORY_OPTS="-Dspark.eventLog.enabled=true -Dspark.eventLog.dir=/opt/bitnami/spark/spark-events 
      networks:
        - spark-network
    spark-history-server:
      image: bitnami/spark:latest  # Match master/worker version
      container_name: spark-history-server
      depends_on:
        - sparkmaster
      command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
      environment:
        - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/tmp/spark-events
        - SPARK_HISTORY_UI_PORT=18080  # Split into separate options
      mem_limit: 2g
      mem_reservation: 1g
      cpus: "1"
      ports:
        - "18080:18080"  # History Server UI
      networks:
        - spark-network
      volumes:
        - ./spark_events:/tmp/spark-events  # Access event logs

  volumes:
    spark_data:
    spark_event:

  networks:
    spark-network:
      driver: bridge

