version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lohraspco
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: lohcaspco@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lohraspco
    ports:
      - "8090:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
